sudo: required

dist: trusty

language: generic

services:
  - docker

env:
  - TAGS="bcm2708 bcm2709 bcm2710 mt7620 mt76x8 mt7688 mvebu x86-64"

before_script:
  docker build -t easypi/openwrt:base -f Dockerfile.base .

script:
  make build;
  for TAG in $TAGS;
  do
    docker build -t easypi/openwrt:$TAG -f Dockerfile.$TAG .;
  done

after_success:
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push easypi/openwrt;
  docker push easypi/openwrt:base;
  for TAG in $TAGS;
  do
    docker push easypi/openwrt:$TAG;
  done
